services:
    constup_foss_php_serializer_app:
        container_name: constup_foss_php_serializer_app
        build:
            args:
                PROJECTINIT_UID: ${PROJECTINIT_UID}
                PROJECTINIT_GID: ${PROJECTINIT_GID}
            context: ./
            dockerfile: Dockerfile
        image: constup_foss_php_serializer_app
        restart: "unless-stopped"
        ports:
            - "12580:8080"
        volumes:
            - ./:/usr/src/app
            - ./projectinit_docker/dev/php/usr/local/etc/php/conf.d/zz_php.ini:/usr/local/etc/php/conf.d/zz_php.ini
